### ISSUE TITLE
Parsing Error in ClientFramework when Handling Guid Type Fields

### ISSUE THREAD

**Issue by wortho** [NAVPERF/NAVLoadTest#22]
When opening a Page with a Guid Type Field the ClientFramework fails to parse the Json response.
ClientLogicalControl.BuildCore fails when calling ReadObjectValue(ClientLogicalControl.ObjectValuePropertyName.Resolve(context), data);

The Error happens when trying to JsonData convert the string to a Guid type.

The error occurs in Microsoft.Dynamics.Framework.UI.Client

**Comment by wortho** [comment]
Freddy have you had a chance to look into this. It is a blocker for and pages using guid fields.

**Comment by wortho** [comment]
Hi Freddy. Have the client team had a chance to look at this? It is still an issue with the latest NAV 2016 CU.
It might be specific the customers customization but it seems like a fairly generic error when opening a page with a Guid field displayed.

**Comment by wortho** [comment]
Sorry I closed accidentally.

**Comment by wortho** [comment]
It appears that the problem is not related to any Guid fields displayed on a page but specifically to fields that have a lookup table relation to another Guid field.

**Comment by wortho** [comment]
I have been able to repro the problem in NAV 2016 CU18 using the standard image with demo database. To repro you can add a Guid field to the Customer Table (18) and then add the Guid field to the CustomerCard Page (21). 
After that you can no longer open the Customer Card (21) page using the OpenFormInteraction.

**Comment by wortho** [comment]
Here is the interesting part of the stack trace when it fails to parse the Guid field...

`System.InvalidCastException: Invalid cast from 'System.String' to 'System.Guid'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Microsoft.Dynamics.Framework.UI.Client.JsonDataObject.GetProperty[T](String propertyName, T defaultValue) in s:\Depot\NAV90\Platform\Client\ClientService\Prod.Client.ClientService.Client\Service\Serialization\Json\JsonDataObject.cs:line 106
   at Microsoft.Dynamics.Framework.UI.Client.ClientGuidControl.ReadObjectValue(String propertyName, IDataObject dataObject) in s:\Depot\NAV90\Platform\Client\ClientService\Prod.Client.ClientService.Client\LogicalControls\EditControls\ClientGuidControl.Builder.cs:line 24
   at Microsoft.Dynamics.Framework.UI.Client.ClientLogicalControl.BuildCore(IDataObject data, DataObjectContext context) in s:\Depot\NAV90\Platform\Client\ClientService\Prod.Client.ClientService.Client\LogicalControls\ClientLogicalControl.Builder.cs:line 32`

**Comment by wortho** [comment]
In the Json response to the request the actual field looks like this...
`{
    "t": "guc",
    "Id": "1E90",
    "c": "TestData",
    "sv": "{d43227be-4c19-4060-8280-736c740a332a}",
    "ov": "d43227be-4c19-4060-8280-736c740a332a",
    "ed": false,
    "cid": "{00000015-0000-003F-0008-0000836BD2D2}",
    "h": {},
    "w": {
      "mi": 10,
      "p": 30,
      "ma": 60
    },
    "f": {}
  }`

**Comment by wortho** [comment]
This got fixed in NAV 2018. Internal bug #233819.
